### ISSUE TITLE
개인 정보 보호

### ISSUE THREAD

**Issue by AlvinYou** [zzinpan/portfolio#1]
민감한 데이터 제거
- [x] 생일
- [x] 연락처
- [x] 주소

**Comment by zzinpan** [comment]
생일도 민감한가요?

연락처는 제거하였습니다.

주소는 더 간략히 적었습니다.

**Comment by AlvinYou** [comment]
회사마다 다르겠지만, 개인의 상세정보들을 적지않는것이 추세로 보입니다.
가능하다면 본인을 어필할 수 있는 채널(블로그 깃허브 등)과 이메일만 오픈하는 것 같아요
