### ISSUE TITLE
Header Menu

### ISSUE THREAD

**Issue by AlvinYou** [zzinpan/portfolio#2]
header menu 내에 padding 클릭시 페이지 전환이 되지 않음
이벤트 리스너 위치 변경 필요

**Comment by zzinpan** [comment]
확인한 시점이 아마, 이벤트 리스너가 없는 상태였을 것입니다.
현재는 로컬에서 개발하여, 원격에 반영해둘 예정입니다.

a 태그의 href 속성만을 이용하였는데,
css 애니메이션을 부모 요소에 넣어두어서, 이상하다고 판단하신 것같습니다.

사실, 문제는 미완성 코드를 원격에 반영한 것이 잘못이죠...
이건 반성해야겠네요.😥

다음에는 라인 링크를 부탁드립니다.
