### ISSUE TITLE
데모 데이터

### ISSUE THREAD

**Issue by AlvinYou** [zzinpan/portfolio#3]
데모 소개 페이지 내에서 프로젝트 기여도(bar)와 특이사항의 %가 서로 매치가 안되어 정확한 파악이 어려워보입니다.

**Comment by AlvinYou** [comment]
내용도 가독성을 높이기 위해 Bold체를 필요할때만 사용하는 것이 어떨가 싶습니다.

**Comment by zzinpan** [comment]
> 데모 소개 페이지 내에서 프로젝트 기여도(bar)와 특이사항의 %가 서로 매치가 안되어 정확한 파악이 어려워보입니다.

프로젝트에는 기획/개발 뿐아니라 여러가지 요소가 포함됩니다.
예를들면, 디자인, 모델링, 검증, 배포 등이요.

기여도가 100%인 경우, 모든 항목을 온전히 저 혼자 진행한 것이고,
그렇지 않은 경우에도, 기획과 개발은 온전히 제가 했던 경험입니다.
충분히 헷갈릴 수 있을 것같은데, 고민 좀 해보겠습니다.

다음에는 라인 링크를 부탁드립니다.

**Comment by zzinpan** [comment]
> 내용도 가독성을 높이기 위해 Bold체를 필요할때만 사용하는 것이 어떨가 싶습니다.

https://github.com/zzinpan/portfolio/issues/4 - 해당 이슈에 항목 추가하였습니다.
